# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- libtensor-dev

pool:
  vmImage: ubuntu-20.04

jobs:
- job: build

  steps:
  - script: |
      mkdir /tmp/gtest
      env -C /tmp/gtest cmake /usr/src/googletest -DCMAKE_CXX_FLAGS=-std=c++11 -Dgtest_disable_pthreads=1
      env -C /tmp/gtest make -j $(nproc)
      env -C /tmp/gtest sudo make install

  - script: ./configure --examples --tests --benchmarks
  - script: make $(nproc)
  - script: make test
