# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- libtensor-dev

jobs:
- job: build
  strategy:
    matrix:
      ubuntu-18.04:
        imageName: 'ubuntu-18.04'

      ubuntu-20.04:
        imageName: 'ubuntu-20.04'

  pool:
    vmImage: $(imageName)

  steps:
  - script: sudo apt install -y libgtest-dev libbenchmark-dev
  - script: |
      mkdir /tmp/gtest
      env -C /tmp/gtest cmake /usr/src/googletest -DCMAKE_CXX_FLAGS=-std=c++11 -Dgtest_disable_pthreads=1
      env -C /tmp/gtest make -j $(nproc)
      env -C /tmp/gtest sudo make install

  - script: ./configure --examples --tests --benchmarks
  - script: make -j $(nproc)
  - script: make test

- job: release
  strategy:
    matrix:
      ubuntu-18.04:
        imageName: 'ubuntu-18.04'

  pool:
    vmImage: $(imageName)

  steps:
  - script: ./configure --release=v$(git log -1 --format=%ct)
  - script: make -j $(nproc)
  - script: make package
