SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "lg4869@outlook.com")
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_PACKAGE_DIRECTORY ${CMAKE_SOURCE_DIR}/release)
SET(CPACK_PACKAGE_VERSION
    "latest"
    CACHE STRING "Release version.")
IF(BUILD_DEB)
    SET(CPACK_GENERATOR "TGZ;DEB")
    # SET(CPACK_GENERATOR "TGZ;RPM")
ENDIF()
INCLUDE(CPack)
